"""Add sandbox fields to Lab model

Revision ID: 1db285ab4bb6
Revises: 
Create Date: 2025-06-28 14:35:23.711040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db285ab4bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sandbox_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sandbox_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_column('sandbox_instructions')
        batch_op.drop_column('sandbox_url')

    # ### end Alembic commands ###
