"""Add marks to LabQuizQuestion and hacking fields to Lab

Revision ID: 35c3043fb8f5
Revises: 1db285ab4bb6
Create Date: 2025-06-28 14:47:35.160321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c3043fb8f5'
down_revision = '1db285ab4bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_command', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('command_success_criteria', sa.Text(), nullable=True))

    with op.batch_alter_table('lab_quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_quiz_question', schema=None) as batch_op:
        batch_op.drop_column('marks')

    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_column('command_success_criteria')
        batch_op.drop_column('required_command')

    # ### end Alembic commands ###
