"""Add password reset fields to User

Revision ID: 92b24b1858dd
Revises: 
Create Date: 2025-06-29 18:16:13.756232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b24b1858dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_expiry')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
