"""Add terminal lab fields to Lab model

Revision ID: ee9663c65d72
Revises: 91fe2283aea2
Create Date: 2025-06-29 10:11:09.717310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9663c65d72'
down_revision = '91fe2283aea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('terminal_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terminal_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('terminal_shell', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('terminal_timeout', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_command_hints', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('strict_order', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_retry', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_column('allow_retry')
        batch_op.drop_column('strict_order')
        batch_op.drop_column('allow_command_hints')
        batch_op.drop_column('terminal_timeout')
        batch_op.drop_column('terminal_shell')
        batch_op.drop_column('terminal_instructions')
        batch_op.drop_column('terminal_enabled')
        batch_op.drop_column('lab_type')

    # ### end Alembic commands ###
