"""empty message

Revision ID: f55fe39ae38b
Revises: 92b24b1858dd
Create Date: 2025-07-14 09:50:40.097740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f55fe39ae38b'
down_revision = '92b24b1858dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], name='chat_user1_id_fkey'),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], name='chat_user2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_pkey')
    )
    # ### end Alembic commands ###
